# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/ee26/lab2/lab2/lab2.cache/wt [current_project]
set_property parent.project_path Z:/ee26/lab2/lab2/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo z:/ee26/lab2/lab2/lab2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  Z:/ee26/lab2/lab2/lab2.srcs/sources_1/new/block_a.vhd
  Z:/ee26/lab2/lab2/lab2.srcs/sources_1/new/block_b.vhd
  Z:/ee26/lab2/lab2/lab2.srcs/sources_1/new/block_c.vhd
  Z:/ee26/lab2/lab2/lab2.srcs/sources_1/new/claa2_4bit.vhd
  Z:/ee26/lab2/lab2/lab2.srcs/sources_1/new/parallel_claa_16bit.vhd
  Z:/ee26/lab2/lab2/lab2.srcs/sources_1/new/use_claa_from_rom.vhd
}
read_ip -quiet z:/ee26/lab2/lab2/lab2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all z:/ee26/lab2/lab2/lab2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top use_claa_from_rom -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef use_claa_from_rom.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file use_claa_from_rom_utilization_synth.rpt -pb use_claa_from_rom_utilization_synth.pb"
