# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kptho/Desktop/Spring 2020 Semester/EE 26/Labs/EE-26-Lab-Project-Repo/lab4/lab4.srcs/sources_1/ip/fp_multiplier/fp_multiplier.xci
# IP: The module: 'fp_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kptho/Desktop/Spring 2020 Semester/EE 26/Labs/EE-26-Lab-Project-Repo/lab4/lab4.srcs/sources_1/ip/fp_multiplier/fp_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_multiplier'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/kptho/Desktop/Spring 2020 Semester/EE 26/Labs/EE-26-Lab-Project-Repo/lab4/lab4.srcs/sources_1/ip/fp_multiplier/fp_multiplier.xci
# IP: The module: 'fp_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kptho/Desktop/Spring 2020 Semester/EE 26/Labs/EE-26-Lab-Project-Repo/lab4/lab4.srcs/sources_1/ip/fp_multiplier/fp_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
