# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fft_constraints.xdc

# IP: ip/fp_multiplier/fp_multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_multiplier || ORIG_REF_NAME==fp_multiplier} -quiet] -quiet

# IP: ip/fp_adder_subtractor/fp_adder_subtractor.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_adder_subtractor || ORIG_REF_NAME==fp_adder_subtractor} -quiet] -quiet
